# Generated by Django 3.2.16 on 2023-01-01 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_num', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('penal_charge', models.FloatField()),
                ('minimum_loan_amount', models.IntegerField()),
                ('max_loan_amount', models.IntegerField(default=500000)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.providerconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('principal_amount', models.FloatField()),
                ('tenure', models.IntegerField(default=12)),
                ('start_date', models.DateField()),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.customer')),
                ('provider_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.provider')),
            ],
        ),
    ]
